auto: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
paginate: 8
permalink: /:title

title: Ceylog
url: http://ceylog.github.io
feed: /atom.xml
author_info: <a href="http://ceylog.github.io/">Ceylog</a>
